# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 03:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bizcontacts', '0002_auto_20171116_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='website',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
