# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 21:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bizcontacts', '0003_auto_20171118_1459'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='back',
            new_name='back_url',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='front',
            new_name='front_url',
        ),
    ]
