# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bizcontacts', '0003_contact_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='back_url',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
